// equipmentData.js

export const possibleEquipment = [
    {
      name: 'Hammock',
      type: 'equipment',
      manufacturer: 'SpaceX',
      keyName: 'bed',
      material: 'bed',
      installable: true,
      detachable: true,
      configurable: false,
      section: 'interior',
      iconType: 'bed',
      iconColor: 'white',
      condition: 'New',
      description: 'Basic sleeping area.',
      stackSize: 1
    },
    {
      name: 'ECLSS',
      type: 'equipment',
      manufacturer: 'SpaceX',
      keyName: 'basicLifeSupport',
      material: 'basic-life-support',
      installable: true,
      detachable: false,
      configurable: false,
      status: true,
      section: 'interior',
      iconType: 'life-buoy',
      iconColor: 'white',
      condition: 'Operational',
      storage: { oxygen: 20, water: 70 }, // @ 0.84kg & 4.5kg /person-day
      utilityRate: { power: -0.2 },
      efficiencyRate: { water: 0.95 },
      description: 'Environmental Control and Life Support System. Built-in.',
      stackSize: 1
    },
    {
      name: 'Solar Panels',
      type: 'equipment',
      manufacturer: 'SpaceX',
      keyName: 'solarArray',
      material: 'solar-panel',
      installable: true,
      detachable: false,
      configurable: false,
      status: true,
      section: 'exterior',
      iconType: 'sun',
      iconColor: 'white',
      condition: 'New',
      utilityRate: { power: 2 }, // @ kW
      description: 'Generates solar power. Built-in.',
      stackSize: 1
    },
    {
      name: 'Food Storage',
      type: 'equipment',
      manufacturer: 'SpaceX',
      keyName: 'foodStorage',
      material: 'food-storage',
      installable: true,
      detachable: true,
      configurable: false,
      section: 'interior',
      iconType: 'utensils',
      iconColor: 'white',
      condition: 'New',
      storage: { food: 405 }, // 215 @ 2.39/person-day, but 1 meal each = 180
      description: 'Stores food rations for crew members.',
      stackSize: 1
    },
    {
      name: 'Airlock',
      type: 'equipment',
      manufacturer: 'SpaceX',
      keyName: 'airlock',
      sharedStatus: 'airlock',
      material: 'airlock',
      installable: true,
      detachable: false,
      configurable: true,
      status: true,
      statusLock: false,
      section: [ 'interior', 'exterior' ],
      iconType: 'door-open',
      iconColor: 'white',
      condition: 'used',
      utilityRate: { power: -0.05 },
      description: 'Airlock. Built-in.',
      stackSize: 1
    },
    {
      name: 'Draco (RCS)',
      type: 'equipment',
      manufacturer: 'SpaceX',
      keyName: 'rcsSystem',
      material: 'rcs-system',
      installable: true,
      detachable: false,
      configurable: false,
      status: true,
      statusLock: true,
      section: 'exterior',
      iconType: 'fuel',
      iconColor: 'orange',
      condition: 'Operational',
      storage: { fuel: 100 },
      utilityRate: { power: -0.05 },
      fuelConsumption: { fuel: -5 },
      description: 'Reaction Control System used for attitude control and orientation. Built-in.',
      stackSize: 1
    },
    {
      name: 'Lithium-Ion Battery Pack',
      type: 'equipment',
      manufacturer: 'SpaceX',
      keyName: 'liIonBattery',
      material: 'battery',
      installable: true,
      detachable: false,
      configurable: false,
      status: true,
      statusLock: false,
      section: 'exterior',
      iconType: 'battery-full',
      iconColor: 'blue',
      condition: 'Operational',
      storage: { power: 4 },  // Power storage in watts (4 kWh = 4000 W)
      description: 'Stores power for use during periods without solar exposure. Built-in.',
      stackSize: 1
    },
    {
      name: 'Hatch',
      type: 'equipment',
      keyName: 'front-door',
      sharedStatus: 'hatch',
      material: 'bulkhead',
      installable: true,
      detachable: false,
      configurable: false,
      status: true,
      statusLock: false,
      section: [ 'interior', 'exterior' ],
      iconType: 'door-closed',
      iconColor: 'blue',
      condition: 'Operational',
      description: 'Side access hatch. Built-in.',
      stackSize: 1
    }
    // Add more equipment as needed
  ];  

// Template
// name: 'Lithium-Ion Battery Pack',
// type: 'equipment',
// keyName: 'liIonBattery',
// material: 'battery',
// installable: true | false,
// uninstallable: true | false,
// section: 'exterior',
// iconType: 'battery-full',
// iconColor: 'blue',
// condition: 'Operational',
// storage: { power: 4000 },  // Power storage in watts (4 kWh = 4000 W)
// description: 'Stores power for use during periods without solar exposure. Built-in.',
// stackSize: 1